api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("consume_api.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

consume_api/urls.py
from django.urls import path
from . import views

app_name = 'consume_api'

urlpatterns = [
    path('', views.main_page, name='home'),
    path('breaking_bad', views.breakin_seasons, name='breaking bad episodes'),
    path('better_call', views.seul_seasons, name='better call saul episodes'),
    path('breaking_episodes/<str:season>/', views.breaking_episodes, name='breakingseason'),
    path('better_call_saul_episodes/<str:season>/', views.seul_episodes, name='saulseason'),
    path('character/<int:id>/', views.get_character, name='Personaje'),
    path('episode/<int:id>/', views.get_episode, name='episode'),
    path('search/', views.search_character, name='search_result')
]

consume_api/models.py
from django.db import models

# Create your models here.

consume_api/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
from django.template import loader
from PIL import Image

# Create your views here.


def main_page(request):
    response_breaking = requests.get(
        'https://tarea-1-breaking-bad.herokuapp.com/api/episodes/?series=Breaking+Bad'
    )
    response = response_breaking.json()
    temporadas_breaking = list()
    for resp in response:
        temporada = resp['season']
        if temporada not in temporadas_breaking:
            temporadas_breaking.append(temporada)
    temporadas_breaking.sort()

    response_seul = requests.get(
      '  https://tarea-1-breaking-bad.herokuapp.com/api/episodes/?series=Better+Call+Saul'
    )
    response = response_seul.json()
    temporadas_saul = list()
    for resp in response:
        temporada = resp['season']
        if temporada not in temporadas_saul:
            temporadas_saul.append(temporada)
    temporadas_saul.sort()
    context = {
        'temporadas_breaking': temporadas_breaking,
        'temporadas_saul': temporadas_saul
    }

    return render(request, 'consume_api/home.html', context)


def breakin_seasons(request):
    response_breaking = requests.get(
        'https://tarea-1-breaking-bad.herokuapp.com/api/episodes/?series=Breaking+Bad'
    )
    response = response_breaking.json()
    temporadas = list()
    for resp in response:
        temporada = resp['season']
        if temporada not in temporadas:
            temporadas.append(temporada)
    temporadas.sort()
    context = {
        'response': response,
        'temporadas': temporadas
    }
    return render(request, 'consume_api/seasons.html', context)


def seul_seasons(request):
    response_seul = requests.get(
      '  https://tarea-1-breaking-bad.herokuapp.com/api/episodes/?series=Better+Call+Saul'
    )
    response = response_seul.json()
    temporadas = list()
    for resp in response:
        temporada = resp['season']
        print(temporada)
        if temporada not in temporadas:
            temporadas.append(temporada)
    temporadas.sort()
    context = {
        'response': response,
        'temporadas': temporadas
    }
    return render(request, 'consume_api/seasons.html', context)


def breaking_episodes(request, season):
    url = 'https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Breaking+Bad'
    response = requests.get(url)
    response = response.json()
    content = list()
    for r in response:     
        if r['season'] == season:
            content.append(r)

    context = {
        'content': content
    }
    return render(request, 'consume_api/episodes.html', context)


def seul_episodes(request, season):
    url = 'https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Better+Call+Saul'
    response = requests.get(url)
    response = response.json()
    content = list()
    for r in response:     
        if r['season'] == season:
            content.append(r)

    context = {
        'content': content
    }
    return render(request, 'consume_api/episodes.html', context)


def get_character(request, id):
    url = f'https://tarea-1-breaking-bad.herokuapp.com/api/characters/{id}'
    character_details = requests.get(url)
    character_details = character_details.json()[0]
    name = character_details['name']
    name = name.replace(' ', '+')
    url_quote = f'https://tarea-1-breaking-bad.herokuapp.com/api/quote?author={name}'
    character_quotes = requests.get(url_quote)
    character_quotes = character_quotes.json()
    context = {
        'name': character_details['name'],
        'occupation': character_details['occupation'],
        'status': character_details['status'],
        'nickname': character_details['nickname'],
        'appearance': character_details['appearance'],
        'portrayed': character_details['portrayed'],
        'category': character_details['category'],
        'better_call_saul_appearance': character_details['better_call_saul_appearance'],
        'quotes': character_quotes,
        'img': character_details['img']
    }
    return render(request, 'consume_api/character.html', context)


def get_episode(request, id):
    url = f'https://tarea-1-breaking-bad.herokuapp.com/api/episodes/{id}'
    episode_detail = requests.get(url)
    episode_detail = episode_detail.json()[0]
    phone_book = dict()
    for personaje in episode_detail['characters']:
        name = personaje.replace(' ', '+')
        url_personaje = f'https://tarea-1-breaking-bad.herokuapp.com/api/characters?name={name}'
        personaje = requests.get(url_personaje)
        personaje = personaje.json()[0]
        phone_book[personaje['char_id']] = personaje['name']
    context = {
        'title': episode_detail['title'],
        'season': episode_detail['season'],
        'air_date': episode_detail['air_date'],
        'characters': episode_detail['characters'],
        'episode': episode_detail['episode'],
        'series': episode_detail['series'],
        'phone_book': phone_book
    }
    return render(request, 'consume_api/episode_detail.html', context)


def search_character(request):
    search = request.GET['query']
    search = search.replace(' ', '+')
    url = f'https://tarea-1-breaking-bad.herokuapp.com/api/characters?name={search}'
    characters = requests.get(url)
    characters = characters.json()
    personajes = list()
    for character in characters:
        personajes.append(character)

    context = {
        'personajes': personajes
    }
    return render(request, 'consume_api/search.html', context)

consume_api/templates/consume_api/character.html
<h1>{{ name }}</h1>
<body>
    <form action="{% url 'consume_api:search_result' %}" method="get">
        <input type="text" name="query" placeholder="Buscar personaje...">
        <button type="submit" name="button"> Buscar</button>
    </form>
</body>
<img src={{ img }}>

<li> Ocupacion: </li>
{% for oc in occupation %}
<ul> {{ oc }} </ul>
{% endfor %}
<li> Estado: {{ status }}</li>
<li> Sobrenombre: {{ nickname }}</li>
<li> Temporadas de breaking bad en las que aparece:</li>
{% for ap in appearance%}
<ul><a href="{% url 'consume_api:breakingseason' ap %}"> {{ ap }}</a></ul>
{% endfor %}
<li> Actor: {{ portrayed }}</li>
<li> Series en las que aparece: {{ category }}</li>
<li> Temporadas de better call saul en las que aparece:</li>
{% for aps in better_call_saul_appearance%}
<ul><a href="{% url 'consume_api:saulseason' aps %}"> {{ aps }}</a></ul>
{% endfor %}
<li> Citas:
    {% for quote in quotes%}
     <ul>{{ quote.quote }}</ul>
     {% endfor %}
</li>

consume_api/templates/consume_api/episode_detail.html
<h1>{{ title }}</h1>
<body>
    <form action="{% url 'consume_api:search_result' %}" method="get">
        <input type="text" name="query" placeholder="Buscar personaje...">
        <button type="submit" name="button"> Buscar</button>
    </form>
</body>
<h2> Detalles del episodio: </h2>
<li>Temporada: {{ season }}</li>
<li>Fecha de estreno: {{ air_date }} </li>
<li>Personajes: </li>
{% for key, value in phone_book.items %}
  <ul><li><a href="{% url 'consume_api:Personaje' key %}">{{value}}</a></li></ul>
{% endfor %}
<li>Capitulo numero {{ episode }}</li>
<li>Serie: {{ series }}</li>

consume_api/templates/consume_api/episodes.html
<h1>Capitulos de la temporada: </h1>
<body>
    <form action="{% url 'consume_api:search_result' %}" method="get">
        <input type="text" name="query" placeholder="Buscar personaje...">
        <button type="submit" name="button"> Buscar</button>
    </form>
</body>
{% for episode in content %}
<li><a href="{% url 'consume_api:episode' episode.episode_id %}">{{episode.title}}</a></li>
{% endfor %}

consume_api/templates/consume_api/home.html
<h1>Bienvenido a la tarea 1</h1>

<body>
    <form action="{% url 'consume_api:search_result' %}" method="get">
        <input type="text" name="query" placeholder="Buscar personaje...">
        <button type="submit" name="button"> Buscar</button>
    </form>
</body>
<!-- <button type="submit" onclick="location.href='breaking_bad'">
    Presione aqui para breaking bad
</button>
<button type="submit" onclick="location.href='better_call'">
    Presione aqui para better call saul
</button> -->
<h2>Temporadas de Breaking Bad:</h2>
{% for temporada in temporadas_breaking %}
<li><a href="{% url 'consume_api:breakingseason' temporada %}">Temporada {{temporada}}</a></li>
{% endfor %}

<h2>Temporadas de Better Call Saul:</h2>
{% for temporada in temporadas_saul %}
<li><a href="{% url 'consume_api:saulseason' temporada %}">Temporada {{temporada}}</a></li>
{% endfor %}

consume_api/templates/consume_api/search.html
<h1>Resultado de la busqueda: </h1>
<body>
    <form action="{% url 'consume_api:search_result' %}" method="get">
        <input type="text" name="query" placeholder="Buscar personaje...">
        <button type="submit" name="button"> Buscar</button>
    </form>
</body>
{% for personaje in personajes %}
<li><a href="{% url 'consume_api:Personaje' personaje.char_id %}">{{personaje.name}}</a></li>
{% endfor %}

consume_api/templates/consume_api/seasons.html
<ul>
     {% for temporada in temporadas %}
     <ul><a href="{% url 'consume_api:breakingseason' temporada %}"> Temporada {{ temporada }}</a></ul>
    {% endfor %}
</ul>